vagrant ansible
bokhanych/tms pull request #14
Opened 2022-10-05 20:07 UTC by bokhanych

Привет, нужна помощь с ключами ssh. Подключение по ssh подразумевается под root. Все серверы должны иметь возможность подключиться по ssh друг к другу.

В данной конфигурации :
- на первом сервере я генерирую id_rsa и id_rsa.pub; id_rsa.pub отправляю в общую папку /vagrant и в authorized_keys, чтобы к этому серверу было подключение по этому ключу
- на остальных серверах публичный ключ id_rsa.pub с общей папки вставляю в authorized_keys (/root/.ssh/authorized_keys)

Но, в итоге, не могу подключиться по ssh под\на root между серверами. 
Пробовал играться в sshd_config, с другими пользователями.. кароч, я застрял. 
Просьба запустить у себя мой vagrant file и найти где косяк.

root@ansible:~# ssh root@192.168.10.11 -p 2201
ssh: connect to host 192.168.10.11 port 2201: Connection timed out

root@ansible:~# ssh root@192.168.10.11
(...nothing...)

2022-10-06 10:34 UTC, drempost commented
так, хорошо, для начала, не могу понять, откуда порт 2201....
давай пока остановимся на: 
 - vagrantfile возьми у Алексея: https://github.com/aguranchik/TMS_Homework/pull/10/files    ansible1/Vagrantfile
 - подключаться лучше не под рутом, тк это совсем не безопасно, и иногда может быть запрещено подключение по ssh напрямую к руту
 - репозиторий лучше держать не в /etc/ansible/ , а закинь в home папку мастера

2022-10-09 17:18 UTC, drempost requested changes
так, в целом, все норм, но приватный ключ в гите точно не должен быть, 
публичный тоже не желательно, но приватный удали (можно в .gitignore закинуть)

2022-10-09 17:18 UTC, drempost commented on Ansible/HW14 - ansible.cfg
> +inventory=/etc/ansible/hosts
ты все запускаешь из /etc/ansible/  ?

2022-10-09 17:18 UTC, drempost commented on Ansible/HW14 - ansible.cfg
> +inventory=/etc/ansible/hosts
да, вижу ниже

2022-10-09 17:18 UTC, drempost commented on Ansible/id_rsa
> +-----BEGIN OPENSSH PRIVATE KEY-----
нужно удалить

2022-10-13 13:23 UTC, drempost approved these changes
ok

2022-10-16 13:20 UTC, bokhanych commented
Добавлены блоки в playbook, и добавлены роли (папка roles)

2022-10-16 13:31 UTC, drempost approved these changes
ok

2022-10-16 17:49 UTC, merged