Docker compose
bokhanych/tms pull request #19
Opened 2022-10-23 19:28 UTC by bokhanych

http://www.test-apache.com:80
https://www.test-nginx.com:443 (self-signed SSL)

логирование во внешнюю папку работает

2022-10-23 22:12 UTC, drempost requested changes
есть вопрос по порту в контейнере nginx и нужно убрать все сертификаты/ключи из гита

2022-10-23 22:12 UTC, drempost commented on Docker/nginx/Dockerfile
> +RUN mkdir -p /opt/nginx/logs
сделай вмето трех run один

2022-10-23 22:12 UTC, drempost commented on Docker/nginx/Dockerfile
> +#EXPOSE 443
а как на nginx запросы идут, если порт закрыт?

2022-10-24 06:33 UTC, bokhanych commented on Docker/nginx/Dockerfile
> +#EXPOSE 443
Дмитрий, [23.10.2022 21:16]
и еще вопросик по EXPOSE - если в docker-compose прописаны порты для каждого контейнера, то в dockerfile не нужно вписывать EXPOSE?

Dmitry, [23.10.2022 21:16]
da

Dmitry, [23.10.2022 21:17]
ты там открываешь их

2022-10-24 06:34 UTC, bokhanych commented on Docker/nginx/Dockerfile
> +RUN mkdir -p /opt/nginx/logs
ок
сертификаты уберу, это чисто для демонстрации

2022-10-29 09:45 UTC, drempost approved these changes
ok

2022-11-14 16:37 UTC, merged